### ISSUE TITLE
module not found error 

### ISSUE THREAD

**Issue by muhammadarslanshahzad** [gilikn/FakeOut#2]
while running the inference of the project the following error is encountered in colab 

Traceback (most recent call last):
  File "fakeout/inference.py", line 36, in <module>
    from models import mm_embeddings
  File "/content/drive/MyDrive/Media_Forensics/Fakeout/FakeOut/fakeout/models/mm_embeddings.py", line 25, in <module>
    from fakeout.models import normalization
ModuleNotFoundError: No module named 'fakeout'
<img width="154" alt="image" src="https://user-images.githubusercontent.com/69626496/217113990-7ac461e5-66cf-4aed-8487-c8a6be167c50.png">

where as the files also available in the folder

**Comment by gilikn** [comment]
This is a scope issue. It can be solved in a few ways:
1. Add the following lines to inference.py:
```
import sys
sys.path.append('/content/drive/MyDrive/Media_Forensics/Fakeout/FakeOut')
```
2. Probably replacing ```from fakeout.models import normalization``` with ```from models import normalization``` should work too.

I'll be working on finding a solution (without any "scope patches") for this in an upcoming pull request.
Thank you for bringing this up, let me know if it helped you in the meantime.

**Comment by gilikn** [comment]
Fixed in master branch source code.
